### ISSUE TITLE
Type-safe way to force caller to check Ok/Err Result values

### ISSUE THREAD

**Issue by akdor1154** [rustedpy/result#37]
Hi,
In the static languages that inspire this package, the default way of accessing values is only allowed once you've checked a Result is Ok:
```py
return actuallyAnErr.value # type error!
```

However, in this package, because Ok and Err both share .value, this is by default allowed, and the user is not forced to check that a result is ok.

```py
return actuallyAnError.value # fine, but will confuse the hell out of the caller because we just swallowed an error!
```

Could you consider "blessing" an accessor for value that only exists on Ok, to allow this usage? (Or rename .value on Err to .value_err or something, but that would be another big breaking change...)

Thanks for all your work on this package, I use it in a bunch of places.

**Comment by francium** [comment]
> `return actuallyAnErr.value # type error!`

Are you here suggesting library should throw a Python `TypeError`? Or are you merely hinting that `actuallyAnErr` is an `Err` type?

Either way, so the suggestion is
```
anError = Err('this is an error')
anOk = Ok('this is okay')

# Remove `.value` accessor on Err -- should be instead throw TypeError here as opposed to just removing?
anError.value

# Add `.value_err` accessor
anError.value_err

anOk.value_err # this doesn't exist or should it throw TypeError?
anOk.value === 'this is okay'
```

Would definitely impact anyone relying on current `.value` behavior.

**Comment by akdor1154** [comment]
> > `return actuallyAnErr.value # type error!`
> 
> Are you here suggesting library should throw a Python `TypeError`? Or are you merely hinting that `actuallyAnErr` is an `Err` type?

Library should throw a type error or attribute error, more importantly the definition should be written in a way that mypy flags this as an error.

As an alternative to breaking everybody's `.value` usage, you could create accessor properties e.g. `.ok_value`, `.err_value` that people could opt into using.  `.value` could potentially be deprecated at a later date.

**Comment by francium** [comment]
Actually perhaps what you're after is already implemented,
```
# These two are for the Err variant, you can imagine the Ok variant being just the flipping of the implementation of these two

    def unwrap(self) -> NoReturn:
        """Raises an `UnwrapError`."""
        raise UnwrapError(self, "Called `Result.unwrap()` on an `Err` value")

    def unwrap_err(self) -> E:
        """Return the inner value"""
        return self._value
```

**Comment by akdor1154** [comment]
Very nearly - it's implemented in terms of throwing an error, but it's not implemented in a way that mypy can prevent you doing that in the first place. Maybe to step back a bit, what I want is that

```py
res = getResult()
value = res.value # mypy should flag this line as not ok
```

```py
res = getResult()
if isinstance(res, Ok):
  value = res.value # mypy should let me do this.
```

where `.value` can be replaced by any method of accessing the contents, .unwrap, .val, etc.

This is how results works in Rust, F#, etc - they use the type checker to force you to check if they are ok before accessing.

**Comment by francium** [comment]
> This is how results works in Rust, F#, etc - they use the type checker to force you to check if they are ok before accessing.

> value = res.value # mypy should flag this line as not ok

+1 

sounds like a general type checking improvement then. I have no idea how to do that with mypy off the top of my head, I'd have to dive into the docs and experiment. But if you know mypy better, please feel free to throw up a PR

**Comment by akdor1154** [comment]
> Sound like type narrowing/discriminated union/tagged union. Does mypy handle that?

It actually does, but we don't get to benefit from it here because `.value` exists on both Ok and Err so mypy allows it to be called on `Union[Ok, Err]`.

So if we used (bikeshedding names) `.ok_value` and `.err_value` on Ok and Err, respectively, mypy would disallow `res.ok_value` if you hadn't already checked that `isinstance(res, Ok)`.

**Comment by felixhammerl** [comment]
I've taken the discussions here, because I've had the same annoyance with type checkers complaining about `Ok` being of type `str | None` instead of `str`, and created a fork that is breaking compatibility with the upstream repo in many ways.

https://github.com/felixhammerl/resultify

Since Python does not have the pattern matching capability of Rust, Python's intepretation of `Optional` is *not* compatible with Rust's and it does not quite make sense in my opinion to treat them equally.

**Comment by wbolster** [comment]
ok, let's try to get this one into motion 🙃

rust and its `std::Result` type (https://doc.rust-lang.org/std/result/) have two crucial properties: 

- special syntax to propagate `Err` results to the caller: `?` (question mark)
- `#[must_use]` to force callers to actually check the value.

neither are available in python, so this cannot be translated directly.

but having a type-safe way to use `Result` (mypy rejecting it as the rust compiler would reject it) is definitely useful. one step in that direction is

- #69

...but it is not currently usable, and while this would achieve type narrowing, it would not cover all use cases: the `.value` accessor currently works on both `Ok[T]` and `Err[E]`, and they may be the of the same type (or the attempted operation would work on both `T` and `E`), so this would not _force_ callers to do the right thing.

this means this would still not provide a way to  guarantee that the `Result` return value is correctly checked by the caller.

i see a few paths forward:

- add additional separate accessors

  - e.g. `.ok_value` and `.err_value` as suggested in https://github.com/rustedpy/result/issues/37#issuecomment-809814134
  - (note: exact names bike-sheddable)
  - the `.value` accessors on both `Ok` and `Err` raise a `Warning`, encouraging users to use `.ok_value` and `.err_value` instead, while keeping existing code working
  - pro: explicit
  - con: verbose and (ok, subjectively) ugly and not so elegant
  - con: `.value` would still be there; users will (accidentally) keep (ab)using it even though they shouldn't because warnings are just that, and not everyone has them show up (or reads them) in their CI systems, and even fewer downstream consumers would turn warnings into actual errors in their CI builds.

- only have `Ok.value`, _not_ `Err.value`, and have `Err.err_value` instead.
  - (note: exact names bike-sheddable)
  - pro: clean API that leaves no doubt what is intended
  - pro: no opportunity to _not_ do the right thing: `Err.value` would simply not work anymore, and type checkers _will_ tell you that.
  - con: breaks API compatibility, which will break for many existing users. sure, (pre-1.x) version numbers don't mean anything and [semver is mostly moot anyway](https://hynek.me/articles/semver-will-not-save-you/), but it's still a _very_ breaking change
  - the `Err.value` accessor could raise `DeprecationWarning` for a while before it goes away, but tbh i think it's not the worth the hassle and planning ahead for a small and not-very-new-anymore-and-actually-used-in-practice project like this.

- wild idea: ‘special semi-syntax trick’:
  - make `Ok` instances callable, but _not_ `Err` instances:
    ```python
    res = do_something()
    do_something_with(res())  # only typechecks for `Ok`, fails for `Err`
    ```
  - pro: very short, bit like the special `?` syntax in rust (but for the happy path, not the error path)
  - con: confusing
  - con: not that different from less confusing but more verbose `.ok_value`

personally i think that option 1 is the most reasonable, but i am not overly enthusiastic to encourage using the rather verbose and slightly ugly `res.ok_value` as the _best_ pattern to use this library.

**Comment by noxasaxon** [comment]
In my opinion, the reason many people love rust is because the compiler forces you to do the right thing. The closest thing Python has to that experience is via typing analysis. If the intention of this library (and the `rustedpy` org) is to bring the joys of coding in rust to the Python ecosystem, I think our target audience is probably also people using `mypy`/`pyright` or some other sort of type checking analysis.

For these users, the best developer experience is unfortunately the one that will break existing API compatibility: 
> only have Ok.value, not Err.value, and have Err.err_value instead.

I think its worth it

**Comment by francium** [comment]
Okay, so the proposal in #99 is,
- Deprecate `value`, deprecation warning for 1 or more releases, then raise exception on usage, then total removal
- Add `value` and `err_value` properties that exist only on `Ok` and `Err` respectively

Any objections to this? Any better ideas?

**Comment by akdor1154** [comment]
Ending up with `value` and `err_value` sounds great, deprecating `Err.value` in the interim makes sense. (deprecating `Ok.value` doesn't make sense of course :)). You'd still need a major version bump when you finally remove `Err.value` as well if you follow semver.

**Comment by wbolster** [comment]
> when you make `Err.value` raise an exception on usage

nope, it wouldn't even exist. python will raise `AttributeError` at runtime, but type checkers will just complain that `.value` doesn't exist

**Comment by dogweather** [comment]
It's now possible to force people to check errors using Python 3.10 and Pyright. This combination enables [true exhaustiveness checking](https://dogweather.dev/2022/10/03/i-discovered-that-python-now-can-do-true-match-exhaustiveness-checking/).

Here's a very simple Result implementation that does force the user to always handle the error case: 

* Making the `value` private: https://github.com/dogweather/python-exhaustiveness-adts-monads/blob/master/src/adt_3_result_monad.py
* Accomplish the same thing w/out private variables: https://github.com/dogweather/python-exhaustiveness-adts-monads/blob/master/src/adt_2_result.py#L93-L110

**Comment by francium** [comment]
Is there a reason we've decided to keep `value` around at all?
Isn't the idiomatic thing to force callers to use `ok`/`err`? Given they are variant specific, they're returning an `Ok` or `Err` in a type safe manner already.
Introducing a `ok_value`/`err_value`...what exactly is that giving us that `ok`/`err` aren't already.

If anything, `value`, which looking at the history of this library, is a artifact from the very first version of this library, should be deprecated-and-removed or removed right away since most people would be using a type checker with this library -- you'd hope so.

@wbolster does what I've said make sense? Let's just deprecate/remove `value` and let callers use `ok`/`err`.

**Comment by francium** [comment]
I've made a preview release with this included, if everything looks okay, it will be made into 0.11.0 in the near future
https://pypi.org/project/result/0.11.0rc1/
